'use strict';

// docker-compose.yml generator for the contexa-managed infrastructure stack.
//
// The CLI provisions infrastructure only. Contexa schema and seed data are
// installed by the contexa-iam runtime initializer when the application starts,
// so this compose file intentionally does not mount docker-entrypoint initdb SQL.
//
// `infraDir` MUST be a contexa-owned directory (e.g. ~/.contexa/<projectName>),
// NEVER the customer's project directory. Writing into the customer's project
// directory would clobber any docker-compose.yml the customer may already have
// for their own services, which is the #1 sideeffect we must avoid.
//
// The caller (init.js) resolves `infraDir` via core/project.js#resolveInfraDir.
// Image tags, ports and the compose project name are env-overridable so a
// single host can run multiple stacks side-by-side and operators can pin
// images for production reproducibility.

const fs = require('fs-extra');
const path = require('path');

async function generateDockerCompose(infraDir, opts = {}) {
  const { infra = 'standalone', includeOllama = false } = opts;
  await fs.ensureDir(infraDir);
  const composePath = path.join(infraDir, 'docker-compose.yml');

  // Inside contexa-owned dir we still keep a .bak as a safety net for the
  // unlikely case where the user manually edited the previous output.
  if (await fs.pathExists(composePath)) {
    await fs.copy(composePath, composePath + '.bak');
  }

  let content = `# Contexa Infrastructure - Auto-generated by contexa init
# All container names, ports, image tags and the compose project name are
# env-overridable so that a single host can run multiple stacks side-by-side
# (production + manual install simulation + integration test) without
# colliding, AND so operators can pin image tags for production reproducibility.
#
# Common overrides:
#   CONTEXA_PROJECT                compose project name + container prefix (default "contexa")
#   COMPOSE_BIND_HOST              bind host on the docker host  (default 127.0.0.1)
#   CONTEXA_POSTGRES_PORT          Postgres host port            (default 5432)
#   CONTEXA_OLLAMA_PORT            Ollama host port              (default 11434)  [include-ollama]
#   CONTEXA_REDIS_PORT             Redis host port               (default 6379)  [distributed]
#   CONTEXA_ZOOKEEPER_PORT         Zookeeper host port           (default 2181)  [distributed]
#   CONTEXA_KAFKA_PORT             Kafka host port               (default 9092)  [distributed]
#   CONTEXA_PGVECTOR_IMAGE_TAG     pgvector image tag            (default pg16)
#   CONTEXA_OLLAMA_IMAGE_TAG       ollama image tag              (default latest - PIN IN PROD)
#   CONTEXA_REDIS_IMAGE_TAG        redis image tag               (default 7.2-alpine)
#   CONTEXA_KAFKA_PLATFORM_VERSION confluentinc cp-* version     (default 7.4.0)
name: \${CONTEXA_PROJECT:-contexa}

services:
  # PostgreSQL with PGVector
  postgres:
    image: pgvector/pgvector:\${CONTEXA_PGVECTOR_IMAGE_TAG:-pg16}
    container_name: \${CONTEXA_PROJECT:-contexa}-postgres
    environment:
      POSTGRES_DB: \${CONTEXA_DB_NAME:-contexa}
      POSTGRES_USER: \${CONTEXA_DB_USERNAME:-contexa}
      POSTGRES_PASSWORD: \${CONTEXA_DB_PASSWORD:-contexa1234!@#}
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    ports:
      - "\${COMPOSE_BIND_HOST:-127.0.0.1}:\${CONTEXA_POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${CONTEXA_DB_USERNAME:-contexa} -d \${CONTEXA_DB_NAME:-contexa}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
`;

  if (includeOllama) {
    content += `
  # Ollama - Local LLM runtime for offline / no-API-key operation.
  # Default tag is "latest" for evaluation. Production deployments MUST set
  # CONTEXA_OLLAMA_IMAGE_TAG to a specific version for reproducibility.
  ollama:
    image: ollama/ollama:\${CONTEXA_OLLAMA_IMAGE_TAG:-latest}
    container_name: \${CONTEXA_PROJECT:-contexa}-ollama
    ports:
      - "\${COMPOSE_BIND_HOST:-127.0.0.1}:\${CONTEXA_OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=30m
      - OLLAMA_NUM_PARALLEL=2
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
`;
  }

  if (infra === 'distributed') {
    content += `
  # Redis - Session store, cache, distributed locks (PoC/demo only)
  redis:
    image: redis:\${CONTEXA_REDIS_IMAGE_TAG:-7.2-alpine}
    container_name: \${CONTEXA_PROJECT:-contexa}-redis
    ports:
      - "\${COMPOSE_BIND_HOST:-127.0.0.1}:\${CONTEXA_REDIS_PORT:-6379}:6379"
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Zookeeper - Kafka coordinator
  zookeeper:
    image: confluentinc/cp-zookeeper:\${CONTEXA_KAFKA_PLATFORM_VERSION:-7.4.0}
    container_name: \${CONTEXA_PROJECT:-contexa}-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "\${COMPOSE_BIND_HOST:-127.0.0.1}:\${CONTEXA_ZOOKEEPER_PORT:-2181}:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  # Kafka - Event streaming
  kafka:
    image: confluentinc/cp-kafka:\${CONTEXA_KAFKA_PLATFORM_VERSION:-7.4.0}
    container_name: \${CONTEXA_PROJECT:-contexa}-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:\${CONTEXA_KAFKA_PORT:-9092}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "\${COMPOSE_BIND_HOST:-127.0.0.1}:\${CONTEXA_KAFKA_PORT:-9092}:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
`;
  }

  // Volumes
  content += `
volumes:
  pgdata:`;
  if (includeOllama) {
    content += `
  ollama-data:`;
  }
  if (infra === 'distributed') {
    content += `
  redis-data:
  zookeeper-data:
  kafka-data:`;
  }
  content += '\n';

  await fs.writeFile(composePath, content);
  return composePath;
}

module.exports = { generateDockerCompose };
