'use strict';

// Postgres docker-entrypoint-initdb.d generator.
//   01-core-ddl.sql : full schema for the contexa platform (entity-derived)
//   02-dml.sql      : OSS-safe seed data, including official prompt inspection contracts
//
// Same isolation rule as compose.js: `infraDir` MUST be contexa-owned, never
// the customer's project directory. A defensive .gitignore is dropped beside
// the scripts.
//
// The DDL SQL body lives in templates/ddl.js.

const fs = require('fs-extra');
const path = require('path');

const DDL_SCRIPT = require('./templates/ddl');
const DML_SCRIPT = require('./templates/dml');
const MENU_DML_SCRIPT = require('./templates/menu-dml');
const SYSTEM_SETTINGS_DML_SCRIPT = require('./templates/system-settings-dml');

function getDdlScript() {
  return DDL_SCRIPT;
}

function getDmlScript() {
  return [
    DML_SCRIPT,
    MENU_DML_SCRIPT,
    SYSTEM_SETTINGS_DML_SCRIPT,
  ].join('\n\n');
}

async function generateInitDbScripts(infraDir, opts = {}) {
  const initdbDir = path.join(infraDir, 'initdb');
  await fs.ensureDir(initdbDir);

  // 01-core-ddl.sql (numbered for execution order)
  await fs.writeFile(path.join(initdbDir, '01-core-ddl.sql'), getDdlScript());
  await fs.writeFile(path.join(initdbDir, '02-dml.sql'), getDmlScript());

  // Drop a defensive .gitignore inside initdb/ itself.
  // The "*" line gitignores everything, "!.gitignore" keeps the
  // .gitignore file itself tracked so the protection stays intact across
  // checkouts. Idempotent: do not overwrite a user-customized version.
  const initdbGitignore = path.join(initdbDir, '.gitignore');
  if (!await fs.pathExists(initdbGitignore)) {
    await fs.writeFile(initdbGitignore, [
      '# Generated by contexa-cli init.',
      '*',
      '!.gitignore',
      '',
    ].join('\n'));
  }

  return { initdbDir };
}

module.exports = {
  generateInitDbScripts,
  getDmlScript,
};
