'use strict';

// Postgres docker-entrypoint-initdb.d generator. Two scripts:
//   01-core-ddl.sql : full schema for the contexa platform (entity-derived)
//   02-dml.sql      : seed users + roles + groups + admin menu, with a
//                     freshly randomized BCrypt password hash for the four
//                     seed accounts (admin / kim_manager / park_user / dev_lead)
//
// Same isolation rule as compose.js: `infraDir` MUST be contexa-owned, never
// the customer's project directory. A defensive .gitignore is dropped beside
// the scripts so 02-dml.sql (which contains the BCrypt hash of the seed
// password printed once during init) can never be committed by accident.
//
// The DDL and DML SQL bodies live in templates/{ddl,dml}.js. Splitting them
// out keeps this file small AND makes the SQL searchable as standalone modules
// (grep / IDE outline / future migration tooling all work better that way).

const fs = require('fs-extra');
const path = require('path');
const crypto = require('crypto');
const bcrypt = require('bcryptjs');

const DDL_SCRIPT = require('./templates/ddl');
const DML_TEMPLATE = require('./templates/dml');

// Generate a URL-safe random password (16 chars from 12 random bytes).
// Node 18 supports base64url directly.
function generateRandomPassword(byteLength = 12) {
  return crypto.randomBytes(byteLength).toString('base64url');
}

// BCrypt hash with cost factor 6 to keep init time acceptable.
// Cost 6 is sufficient for the seed accounts; users should rotate later.
function bcryptHash(plain) {
  return bcrypt.hashSync(plain, 6);
}

function getDdlScript() {
  return DDL_SCRIPT;
}

function getDmlScript(seedBcryptHash) {
  if (!seedBcryptHash || typeof seedBcryptHash !== 'string') {
    throw new Error('getDmlScript requires a seedBcryptHash argument');
  }
  return DML_TEMPLATE.split('__SEED_BCRYPT_HASH__').join(seedBcryptHash);
}

async function generateInitDbScripts(infraDir, opts = {}) {
  const initdbDir = path.join(infraDir, 'initdb');
  await fs.ensureDir(initdbDir);

  const seedPassword = opts.seedPassword || generateRandomPassword();
  const seedHash = bcryptHash(seedPassword);

  // 01-core-ddl.sql (numbered for execution order)
  await fs.writeFile(path.join(initdbDir, '01-core-ddl.sql'), getDdlScript());

  // 02-dml.sql with per-init randomized BCrypt hash for the four seed accounts.
  await fs.writeFile(path.join(initdbDir, '02-dml.sql'), getDmlScript(seedHash));

  // Drop a defensive .gitignore inside initdb/ itself: 02-dml.sql contains a
  // BCrypt hash of the freshly generated seed password and must never be
  // committed. The "*" line gitignores everything, "!.gitignore" keeps the
  // .gitignore file itself tracked so the protection stays intact across
  // checkouts. Idempotent: do not overwrite a user-customized version.
  const initdbGitignore = path.join(initdbDir, '.gitignore');
  if (!await fs.pathExists(initdbGitignore)) {
    await fs.writeFile(initdbGitignore, [
      '# Generated by contexa-cli init.',
      '# initdb/02-dml.sql contains a BCrypt hash of a freshly randomized seed',
      '# password and must never be committed. Re-running "contexa init" produces',
      '# a different hash every time.',
      '*',
      '!.gitignore',
      '',
    ].join('\n'));
  }

  return { initdbDir, seedPassword };
}

module.exports = {
  generateInitDbScripts,
  // exported for tests / advanced callers
  generateRandomPassword,
  bcryptHash,
};
