'use strict';

// Postgres docker-entrypoint-initdb.d generator.
//   01-core-ddl.sql : full schema for the contexa platform (entity-derived)
//
// Same isolation rule as compose.js: `infraDir` MUST be contexa-owned, never
// the customer's project directory. A defensive .gitignore is dropped beside
// the scripts.
//
// The DDL SQL body lives in templates/ddl.js.

const fs = require('fs-extra');
const path = require('path');

const DDL_SCRIPT = require('./templates/ddl');

function getDdlScript() {
  return DDL_SCRIPT;
}

async function generateInitDbScripts(infraDir, opts = {}) {
  const initdbDir = path.join(infraDir, 'initdb');
  await fs.ensureDir(initdbDir);

  const isSimulate = opts.simulate || infraDir.includes('ctxa-sim');
  if (isSimulate) {
    const ddlPath = path.join(initdbDir, '01-core-ddl.sql');
    if (await fs.pathExists(ddlPath)) {
      await fs.remove(ddlPath);
    }
    return { initdbDir };
  }

  // 01-core-ddl.sql (numbered for execution order)
  await fs.writeFile(path.join(initdbDir, '01-core-ddl.sql'), getDdlScript());

  // Drop a defensive .gitignore inside initdb/ itself.
  // The "*" line gitignores everything, "!.gitignore" keeps the
  // .gitignore file itself tracked so the protection stays intact across
  // checkouts. Idempotent: do not overwrite a user-customized version.
  const initdbGitignore = path.join(initdbDir, '.gitignore');
  if (!await fs.pathExists(initdbGitignore)) {
    await fs.writeFile(initdbGitignore, [
      '# Generated by contexa-cli init.',
      '*',
      '!.gitignore',
      '',
    ].join('\n'));
  }

  return { initdbDir };
}

module.exports = {
  generateInitDbScripts,
};

