'use strict';

const fs = require('fs-extra');
const path = require('path');

const MARKER_START = '# --- Contexa AI Security ---';
const MARKER_END   = '# --- End Contexa ---';

const CONTEXA_GROUP_ID = 'io.contexa';
const CONTEXA_ARTIFACT_ID = 'spring-boot-starter-contexa';
const CONTEXA_VERSION = '0.1.0';

async function injectYml(ymlPath, opts = {}) {
  const { mode = 'shadow', llmProviders = ['ollama'],
          securityMode = 'full', infra = 'standalone' } = opts;

  // Build spring.ai block based on selected providers
  let aiParts = [];

  if (llmProviders.includes('ollama')) {
    aiParts.push(`    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: qwen2.5:7b
          keep-alive: "24h"
      embedding:
        enabled: true
        model: mxbai-embed-large`);
  }

  if (llmProviders.includes('openai')) {
    aiParts.push(`    openai:
      api-key: \${OPENAI_API_KEY:}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.3
        enabled: true
      embedding:
        enabled: false`);
  }

  if (llmProviders.includes('anthropic')) {
    aiParts.push(`    anthropic:
      api-key: \${ANTHROPIC_API_KEY:}
      chat:
        enabled: true
        options:
          model: claude-sonnet-4-20250514
          temperature: 0.3`);
  } else {
    // Anthropic disabled but api-key dummy required to prevent bean creation failure
    aiParts.push(`    anthropic:
      api-key: \${ANTHROPIC_API_KEY:your-anthropic-api-key}
      chat:
        enabled: false`);
  }

  const aiBlock = `
  ai:
${aiParts.join('\n')}`;

  // Build datasource block
  const dsBlock = `
  datasource:
    url: jdbc:postgresql://localhost:5432/contexa
    username: contexa
    password: contexa1234!@#
    driver-class-name: org.postgresql.Driver`;

  // Build priority from selected providers
  const priority = llmProviders.join(',');

  const block = `\n${MARKER_START}
spring:${dsBlock}
${aiBlock}

contexa:
  zero-trust:
    enabled: true
    ai:
      chat:
        model:
          priority: ${priority}
${MARKER_END}`;

  await fs.ensureDir(path.dirname(ymlPath));

  if (await fs.pathExists(ymlPath)) {
    // Backup original
    await fs.copy(ymlPath, ymlPath + '.bak');

    let content = await fs.readFile(ymlPath, 'utf8');
    const regex = new RegExp(`${escapeRegex(MARKER_START)}[\\s\\S]*?${escapeRegex(MARKER_END)}`);
    content = content.match(regex)
      ? content.replace(regex, block.trim())
      : content + block;
    await fs.writeFile(ymlPath, content);
  } else {
    await fs.writeFile(ymlPath, block.trim());
  }
}

async function injectMavenDep(pomPath) {
  if (!await fs.pathExists(pomPath)) return false;
  let pom = await fs.readFile(pomPath, 'utf8');
  if (pom.includes(CONTEXA_ARTIFACT_ID)) return false;

  // Backup
  await fs.copy(pomPath, pomPath + '.bak');

  const dep = `
        <dependency>
            <groupId>${CONTEXA_GROUP_ID}</groupId>
            <artifactId>${CONTEXA_ARTIFACT_ID}</artifactId>
            <version>${CONTEXA_VERSION}</version>
        </dependency>`;
  pom = pom.replace('</dependencies>', `${dep}\n    </dependencies>`);
  await fs.writeFile(pomPath, pom);
  return true;
}

async function injectGradleDep(gradlePath) {
  if (!await fs.pathExists(gradlePath)) return false;
  let gradle = await fs.readFile(gradlePath, 'utf8');
  if (gradle.includes(CONTEXA_ARTIFACT_ID)) return false;

  // Backup
  await fs.copy(gradlePath, gradlePath + '.bak');

  gradle = gradle.replace(
    /dependencies\s*\{/,
    `dependencies {\n    implementation '${CONTEXA_GROUP_ID}:${CONTEXA_ARTIFACT_ID}:${CONTEXA_VERSION}'`
  );
  await fs.writeFile(gradlePath, gradle);
  return true;
}

async function generateDockerCompose(projectDir, opts = {}) {
  const { infra = 'standalone' } = opts;
  const composePath = path.join(projectDir, 'docker-compose.yml');

  if (await fs.pathExists(composePath)) {
    await fs.copy(composePath, composePath + '.bak');
  }

  let content = `# Contexa Infrastructure - Auto-generated by contexa init
services:
  # PostgreSQL with PGVector
  postgres:
    image: pgvector/pgvector:pg16
    container_name: contexa-postgres
    environment:
      POSTGRES_DB: contexa
      POSTGRES_USER: contexa
      POSTGRES_PASSWORD: contexa1234!@#
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contexa -d contexa"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Ollama - Local LLM for AI security analysis
  ollama:
    image: ollama/ollama:latest
    container_name: contexa-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=30m
      - OLLAMA_NUM_PARALLEL=2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
`;

  if (infra === 'distributed') {
    content += `
  # Redis - Session store, cache, distributed locks
  redis:
    image: redis:7.2-alpine
    container_name: contexa-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Zookeeper - Kafka coordinator
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: contexa-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  # Kafka - Event streaming
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: contexa-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
`;
  }

  // Volumes
  content += `
volumes:
  pgdata:
  ollama-data:`;

  if (infra === 'distributed') {
    content += `
  redis-data:
  zookeeper-data:
  kafka-data:`;
  }

  content += '\n';

  await fs.writeFile(composePath, content);
  return composePath;
}

async function generateInitDbScripts(projectDir, opts = {}) {
  const { enterprise = false } = opts;
  const initdbDir = path.join(projectDir, 'initdb');
  await fs.ensureDir(initdbDir);

  // 01-ddl.sql (numbered for execution order)
  await fs.writeFile(path.join(initdbDir, '01-ddl.sql'), getDdlScript());

  // 02-dml.sql
  await fs.writeFile(path.join(initdbDir, '02-dml.sql'), getDmlScript());

  // 03-enterprise.sql (optional)
  if (enterprise) {
    await fs.writeFile(path.join(initdbDir, '03-enterprise.sql'), getEnterpriseDdlScript());
  }

  return initdbDir;
}

function getDdlScript() {
  return `-- Contexa DDL - Auto-generated by contexa init
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE users (
    id                      BIGSERIAL PRIMARY KEY,
    username                VARCHAR(100) NOT NULL UNIQUE,
    email                   VARCHAR(255) NOT NULL UNIQUE,
    password                VARCHAR(255) NOT NULL,
    name                    VARCHAR(100) NOT NULL,
    phone                   VARCHAR(20),
    department              VARCHAR(100),
    position                VARCHAR(100),
    profile_image_url       VARCHAR(500),
    enabled                 BOOLEAN DEFAULT TRUE NOT NULL,
    account_locked          BOOLEAN DEFAULT FALSE NOT NULL,
    credentials_expired     BOOLEAN DEFAULT FALSE NOT NULL,
    failed_login_attempts   INTEGER DEFAULT 0 NOT NULL,
    lock_expires_at         TIMESTAMP(6),
    mfa_enabled             BOOLEAN DEFAULT FALSE NOT NULL,
    preferred_mfa_factor    VARCHAR(50),
    last_used_mfa_factor    VARCHAR(50),
    last_mfa_used_at        TIMESTAMP(6),
    last_login_at           TIMESTAMP(6),
    last_login_ip           VARCHAR(45),
    password_changed_at     TIMESTAMP(6),
    locale                  VARCHAR(10) DEFAULT 'ko',
    timezone                VARCHAR(50) DEFAULT 'Asia/Seoul',
    created_at              TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP(6)
);
CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_users_department ON users (department);

CREATE TABLE app_group (
    group_id    BIGSERIAL PRIMARY KEY,
    group_name  VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500),
    enabled     BOOLEAN DEFAULT TRUE NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP(6),
    created_by  VARCHAR(100)
);

CREATE TABLE role (
    role_id       BIGSERIAL PRIMARY KEY,
    role_name     VARCHAR(100) NOT NULL UNIQUE,
    role_desc     VARCHAR(500),
    is_expression BOOLEAN DEFAULT FALSE NOT NULL,
    enabled       BOOLEAN DEFAULT TRUE NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP(6),
    created_by    VARCHAR(100)
);

CREATE TABLE managed_resource (
    id                          BIGSERIAL PRIMARY KEY,
    resource_identifier         VARCHAR(512) NOT NULL UNIQUE,
    resource_type               VARCHAR(100) NOT NULL,
    http_method                 VARCHAR(10),
    friendly_name               VARCHAR(255),
    description                 VARCHAR(1024),
    service_owner               VARCHAR(100),
    parameter_types             VARCHAR(255),
    return_type                 VARCHAR(255),
    api_docs_url                VARCHAR(500),
    source_code_location        VARCHAR(500),
    status                      VARCHAR(50) DEFAULT 'NEEDS_DEFINITION' NOT NULL,
    created_at                  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at                  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    available_context_variables VARCHAR(1024)
);

CREATE TABLE permission (
    permission_id        BIGSERIAL PRIMARY KEY,
    permission_name      VARCHAR(255) NOT NULL UNIQUE,
    friendly_name        VARCHAR(255),
    description          VARCHAR(1024),
    target_type          VARCHAR(100),
    action_type          VARCHAR(100),
    condition_expression VARCHAR(2048),
    managed_resource_id  BIGINT UNIQUE REFERENCES managed_resource ON DELETE SET NULL,
    created_at           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP(6)
);

CREATE TABLE user_groups (
    user_id     BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
    group_id    BIGINT NOT NULL REFERENCES app_group ON DELETE CASCADE,
    assigned_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by VARCHAR(100),
    PRIMARY KEY (user_id, group_id)
);

CREATE TABLE group_roles (
    group_id    BIGINT NOT NULL REFERENCES app_group ON DELETE CASCADE,
    role_id     BIGINT NOT NULL REFERENCES role ON DELETE CASCADE,
    assigned_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by VARCHAR(100),
    PRIMARY KEY (group_id, role_id)
);

CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL REFERENCES role ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permission ON DELETE CASCADE,
    assigned_at   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by   VARCHAR(100),
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE policy (
    id                   BIGSERIAL PRIMARY KEY,
    name                 VARCHAR(255) NOT NULL UNIQUE,
    description          VARCHAR(255),
    effect               VARCHAR(255) NOT NULL,
    priority             INTEGER NOT NULL,
    friendly_description VARCHAR(2048),
    ai_model             VARCHAR(255),
    approval_status      VARCHAR(50),
    approved_at          TIMESTAMP(6),
    approved_by          VARCHAR(255),
    confidence_score     DOUBLE PRECISION,
    source               VARCHAR(50),
    updated_at           TIMESTAMP(6),
    created_at           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active            BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE policy_target (
    id                BIGSERIAL PRIMARY KEY,
    policy_id         BIGINT NOT NULL REFERENCES policy ON DELETE CASCADE,
    target_type       VARCHAR(255) NOT NULL,
    target_identifier VARCHAR(255) NOT NULL,
    http_method       VARCHAR(10)
);

CREATE TABLE policy_rule (
    id          BIGSERIAL PRIMARY KEY,
    policy_id   BIGINT NOT NULL REFERENCES policy ON DELETE CASCADE,
    description VARCHAR(255)
);

CREATE TABLE policy_condition (
    id                   BIGSERIAL PRIMARY KEY,
    rule_id              BIGINT NOT NULL REFERENCES policy_rule ON DELETE CASCADE,
    condition_expression VARCHAR(2048) NOT NULL,
    authorization_phase  VARCHAR(255) DEFAULT 'PRE_AUTHORIZE' NOT NULL,
    description          VARCHAR(255)
);

CREATE TABLE role_hierarchy_config (
    id               BIGSERIAL PRIMARY KEY,
    description      VARCHAR(500),
    hierarchy_string TEXT NOT NULL,
    is_active        BOOLEAN DEFAULT FALSE NOT NULL,
    created_at       TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP(6),
    created_by       VARCHAR(100)
);

CREATE TABLE audit_log (
    id                  BIGSERIAL PRIMARY KEY,
    timestamp           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    principal_name      VARCHAR(255) NOT NULL,
    resource_identifier VARCHAR(512) NOT NULL,
    action              VARCHAR(255),
    decision            VARCHAR(255) NOT NULL,
    reason              VARCHAR(1024),
    client_ip           VARCHAR(45),
    details             TEXT,
    outcome             VARCHAR(255),
    resource_uri        VARCHAR(1024),
    parameters          VARCHAR(255),
    session_id          VARCHAR(255),
    status              VARCHAR(255),
    correlation_id      VARCHAR(64),
    event_category      VARCHAR(50),
    event_source        VARCHAR(50),
    http_method         VARCHAR(10),
    request_uri         VARCHAR(2048),
    risk_score          DOUBLE PRECISION,
    user_agent          VARCHAR(512)
);

CREATE TABLE business_resource (
    id            BIGSERIAL PRIMARY KEY,
    name          VARCHAR(255) NOT NULL UNIQUE,
    resource_type VARCHAR(255) NOT NULL,
    description   VARCHAR(1024)
);

CREATE TABLE business_action (
    id          BIGSERIAL PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    action_type VARCHAR(255) NOT NULL,
    description VARCHAR(1024)
);

CREATE TABLE business_resource_action (
    business_resource_id   BIGINT NOT NULL REFERENCES business_resource ON DELETE CASCADE,
    business_action_id     BIGINT NOT NULL REFERENCES business_action ON DELETE CASCADE,
    mapped_permission_name VARCHAR(255) NOT NULL,
    PRIMARY KEY (business_resource_id, business_action_id)
);

CREATE TABLE condition_template (
    id                    BIGSERIAL PRIMARY KEY,
    name                  VARCHAR(255) NOT NULL UNIQUE,
    spel_template         VARCHAR(2048) NOT NULL,
    category              VARCHAR(255),
    parameter_count       INTEGER DEFAULT 0 NOT NULL,
    description           VARCHAR(1024),
    required_target_type  VARCHAR(1024),
    created_at            TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_auto_generated     BOOLEAN,
    is_universal          BOOLEAN,
    source_method         VARCHAR(255),
    template_type         VARCHAR(255),
    updated_at            TIMESTAMP(6),
    approval_required     BOOLEAN,
    classification        VARCHAR(255),
    complexity_score      INTEGER,
    context_dependent     BOOLEAN
);

CREATE TABLE wizard_session (
    session_id    VARCHAR(36) NOT NULL PRIMARY KEY,
    context_data  TEXT NOT NULL,
    owner_user_id VARCHAR(100) NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    expires_at    TIMESTAMP(6) NOT NULL
);

CREATE TABLE function_group (
    id   BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE function_catalog (
    id                  BIGSERIAL PRIMARY KEY,
    description         VARCHAR(1024),
    friendly_name       VARCHAR(255) NOT NULL,
    status              VARCHAR(50) NOT NULL,
    function_group_id   BIGINT REFERENCES function_group,
    managed_resource_id BIGINT NOT NULL UNIQUE REFERENCES managed_resource
);

CREATE TABLE policy_template (
    id                BIGSERIAL PRIMARY KEY,
    category          VARCHAR(255),
    description       VARCHAR(1024),
    name              VARCHAR(255) NOT NULL,
    policy_draft_json JSONB NOT NULL,
    template_id       VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE vector_store (
    id        UUID DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    content   TEXT NOT NULL,
    metadata  JSONB,
    embedding vector(1024)
);
CREATE INDEX vector_store_embedding_idx ON vector_store USING hnsw (embedding vector_cosine_ops);

CREATE TABLE user_behavior_profiles (
    id                      BIGSERIAL PRIMARY KEY,
    cluster_centroid_vector  TEXT,
    cluster_size             INTEGER,
    common_activities        JSON,
    common_ip_ranges         JSON,
    confidence_score         REAL,
    last_updated             TIMESTAMP(6),
    learning_count           INTEGER,
    normal_range_metadata    JSON,
    profile_type             VARCHAR(50) NOT NULL,
    user_id                  VARCHAR(255) NOT NULL,
    vector_cluster_id        VARCHAR(255)
);

CREATE TABLE soar_incidents (
    id           UUID NOT NULL PRIMARY KEY,
    created_at   TIMESTAMP(6) NOT NULL,
    history      TEXT,
    severity     VARCHAR(255),
    status       VARCHAR(255) NOT NULL,
    title        VARCHAR(255) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    description  TEXT,
    incident_id  VARCHAR(255),
    metadata     TEXT,
    type         VARCHAR(255)
);

CREATE TABLE soar_approval_policies (
    id                      BIGSERIAL PRIMARY KEY,
    action_name             VARCHAR(255),
    auto_approve_on_timeout BOOLEAN NOT NULL,
    policy_name             VARCHAR(255) NOT NULL UNIQUE,
    required_approvers      INTEGER NOT NULL,
    required_roles          TEXT,
    severity                VARCHAR(255),
    timeout_minutes         INTEGER NOT NULL
);

CREATE TABLE soar_approval_requests (
    id                   BIGSERIAL PRIMARY KEY,
    action_name          VARCHAR(255) NOT NULL,
    created_at           TIMESTAMP(6) NOT NULL,
    description          TEXT,
    organization_id      VARCHAR(120),
    parameters           TEXT,
    playbook_instance_id VARCHAR(255) NOT NULL,
    required_approvers   INTEGER,
    required_roles       TEXT,
    reviewer_comment     TEXT,
    reviewer_id          VARCHAR(255),
    status               VARCHAR(255) NOT NULL,
    updated_at           TIMESTAMP(6) NOT NULL,
    request_id           VARCHAR(255) NOT NULL UNIQUE,
    action_type          VARCHAR(255),
    approval_comment     TEXT,
    approval_timeout     INTEGER,
    approval_type        VARCHAR(255),
    approved_at          TIMESTAMP(6),
    approved_by          VARCHAR(255),
    incident_id          VARCHAR(255),
    requested_by         VARCHAR(255),
    risk_level           VARCHAR(255),
    session_id           VARCHAR(255),
    tool_name            VARCHAR(255)
);

CREATE TABLE soar_approval_steps (
    id            BIGSERIAL PRIMARY KEY,
    request_id    BIGINT REFERENCES soar_approval_requests,
    step_order    INTEGER NOT NULL,
    required_role VARCHAR(255),
    status        VARCHAR(255) NOT NULL,
    assigned_to   VARCHAR(255),
    completed_at  TIMESTAMP(6),
    created_at    TIMESTAMP(6) NOT NULL
);

CREATE TABLE soar_approval_assignments (
    id           BIGSERIAL PRIMARY KEY,
    step_id      BIGINT REFERENCES soar_approval_steps,
    assignee_id  VARCHAR(255) NOT NULL,
    assigned_at  TIMESTAMP(6) NOT NULL,
    status       VARCHAR(255) NOT NULL,
    responded_at TIMESTAMP(6)
);

CREATE TABLE soar_approval_votes (
    id         BIGSERIAL PRIMARY KEY,
    request_id BIGINT REFERENCES soar_approval_requests,
    voter_id   VARCHAR(255) NOT NULL,
    decision   VARCHAR(255) NOT NULL,
    comment    TEXT,
    voted_at   TIMESTAMP(6) NOT NULL
);

CREATE TABLE approval_notifications (
    id                BIGSERIAL PRIMARY KEY,
    action_required   BOOLEAN NOT NULL,
    action_url        VARCHAR(500),
    created_at        TIMESTAMP(6) NOT NULL,
    expires_at        TIMESTAMP(6),
    group_id          VARCHAR(100),
    is_read           BOOLEAN NOT NULL,
    message           TEXT,
    notification_data TEXT,
    notification_type VARCHAR(50) NOT NULL,
    priority          VARCHAR(20),
    read_at           TIMESTAMP(6),
    read_by           VARCHAR(100),
    request_id        VARCHAR(100) NOT NULL,
    target_role       VARCHAR(50),
    title             VARCHAR(255) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL,
    user_id           VARCHAR(100)
);
CREATE INDEX idx_notification_request_id ON approval_notifications (request_id);
CREATE INDEX idx_notification_user_id ON approval_notifications (user_id);
CREATE INDEX idx_notification_is_read ON approval_notifications (is_read);

CREATE TABLE threat_indicators (
    indicator_id         VARCHAR(255) NOT NULL PRIMARY KEY,
    active               BOOLEAN,
    campaign             VARCHAR(255),
    campaign_id          VARCHAR(255),
    cis_control          VARCHAR(255),
    confidence           DOUBLE PRECISION,
    created_at           TIMESTAMP(6) NOT NULL,
    description          TEXT,
    detected_at          TIMESTAMP(6),
    detection_count      INTEGER,
    expires_at           TIMESTAMP(6),
    false_positive_count INTEGER,
    first_seen           TIMESTAMP(6),
    last_seen            TIMESTAMP(6),
    malware_family       VARCHAR(255),
    mitre_attack_id      VARCHAR(255),
    mitre_tactic         VARCHAR(255),
    mitre_technique      VARCHAR(255),
    nist_csf_category    VARCHAR(255),
    severity             VARCHAR(50) NOT NULL,
    source               VARCHAR(255),
    status               VARCHAR(50),
    threat_actor         VARCHAR(255),
    threat_actor_id      VARCHAR(255),
    threat_score         DOUBLE PRECISION,
    indicator_type       VARCHAR(50) NOT NULL,
    updated_at           TIMESTAMP(6),
    indicator_value      VARCHAR(255) NOT NULL
);

CREATE TABLE indicator_metadata (
    indicator_id VARCHAR(255) NOT NULL REFERENCES threat_indicators,
    meta_value   VARCHAR(255),
    meta_key     VARCHAR(255) NOT NULL,
    PRIMARY KEY (indicator_id, meta_key)
);

CREATE TABLE indicator_tags (
    indicator_id VARCHAR(255) NOT NULL REFERENCES threat_indicators,
    tag          VARCHAR(255)
);

CREATE TABLE related_indicators (
    indicator_id         VARCHAR(255) NOT NULL REFERENCES threat_indicators,
    related_indicator_id VARCHAR(255) NOT NULL REFERENCES threat_indicators,
    PRIMARY KEY (indicator_id, related_indicator_id)
);

CREATE TABLE blocked_user (
    id                   BIGSERIAL PRIMARY KEY,
    block_count          INTEGER NOT NULL,
    blocked_at           TIMESTAMP(6) NOT NULL,
    confidence           DOUBLE PRECISION,
    reasoning            TEXT,
    request_id           VARCHAR(255) NOT NULL UNIQUE,
    resolve_reason       TEXT,
    resolved_action      VARCHAR(255),
    resolved_at          TIMESTAMP(6),
    resolved_by          VARCHAR(255),
    risk_score           DOUBLE PRECISION,
    source_ip            VARCHAR(45),
    status               VARCHAR(50) NOT NULL,
    user_agent           VARCHAR(512),
    user_id              VARCHAR(100) NOT NULL,
    username             VARCHAR(100),
    unblock_requested_at TIMESTAMP(6),
    unblock_reason       TEXT,
    mfa_verified         BOOLEAN,
    mfa_verified_at      TIMESTAMP(6)
);

CREATE TABLE oauth2_authorization (
    id                            VARCHAR(100) NOT NULL PRIMARY KEY,
    registered_client_id          VARCHAR(100) NOT NULL,
    principal_name                VARCHAR(200) NOT NULL,
    authorization_grant_type      VARCHAR(100) NOT NULL,
    authorized_scopes             VARCHAR(1000),
    attributes                    TEXT,
    state                         VARCHAR(500),
    authorization_code_value      TEXT,
    authorization_code_issued_at  TIMESTAMP,
    authorization_code_expires_at TIMESTAMP,
    authorization_code_metadata   TEXT,
    access_token_value            TEXT,
    access_token_issued_at        TIMESTAMP,
    access_token_expires_at       TIMESTAMP,
    access_token_metadata         TEXT,
    access_token_type             VARCHAR(100),
    access_token_scopes           VARCHAR(1000),
    oidc_id_token_value           TEXT,
    oidc_id_token_issued_at       TIMESTAMP,
    oidc_id_token_expires_at      TIMESTAMP,
    oidc_id_token_metadata        TEXT,
    refresh_token_value           TEXT,
    refresh_token_issued_at       TIMESTAMP,
    refresh_token_expires_at      TIMESTAMP,
    refresh_token_metadata        TEXT,
    user_code_value               TEXT,
    user_code_issued_at           TIMESTAMP,
    user_code_expires_at          TIMESTAMP,
    user_code_metadata            TEXT,
    device_code_value             TEXT,
    device_code_issued_at         TIMESTAMP,
    device_code_expires_at        TIMESTAMP,
    device_code_metadata          TEXT
);

CREATE TABLE oauth2_registered_client (
    id                            VARCHAR(100) NOT NULL PRIMARY KEY,
    client_id                     VARCHAR(100) NOT NULL,
    client_id_issued_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    client_secret                 VARCHAR(200),
    client_secret_expires_at      TIMESTAMP,
    client_name                   VARCHAR(200) NOT NULL,
    client_authentication_methods VARCHAR(1000) NOT NULL,
    authorization_grant_types     VARCHAR(1000) NOT NULL,
    redirect_uris                 VARCHAR(1000),
    post_logout_redirect_uris     VARCHAR(1000),
    scopes                        VARCHAR(1000) NOT NULL,
    client_settings               VARCHAR(2000) NOT NULL,
    token_settings                VARCHAR(2000) NOT NULL
);

CREATE TABLE user_credentials (
    credential_id                VARCHAR(1000) NOT NULL PRIMARY KEY,
    user_entity_user_id          VARCHAR(1000) NOT NULL,
    public_key                   BYTEA NOT NULL,
    signature_count              BIGINT,
    uv_initialized               BOOLEAN,
    backup_eligible              BOOLEAN NOT NULL,
    authenticator_transports     VARCHAR(1000),
    public_key_credential_type   VARCHAR(100),
    backup_state                 BOOLEAN NOT NULL,
    attestation_object           BYTEA,
    attestation_client_data_json BYTEA,
    created                      TIMESTAMP,
    last_used                    TIMESTAMP,
    label                        VARCHAR(1000) NOT NULL
);

CREATE TABLE user_entities (
    id           VARCHAR(1000) NOT NULL PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    display_name VARCHAR(200)
);

CREATE TABLE one_time_tokens (
    token_value VARCHAR(36) NOT NULL PRIMARY KEY,
    username    VARCHAR(50) NOT NULL,
    expires_at  TIMESTAMP NOT NULL
);
`;
}

function getDmlScript() {
  return `-- Contexa Initial Data
INSERT INTO role (role_name, role_desc, is_expression, enabled, created_at, created_by) VALUES
    ('ROLE_ADMIN',     'System administrator with full access',    FALSE, TRUE, CURRENT_TIMESTAMP, 'SYSTEM'),
    ('ROLE_MANAGER',   'Manager with team-level access',           FALSE, TRUE, CURRENT_TIMESTAMP, 'SYSTEM'),
    ('ROLE_USER',      'Standard user with basic access',          FALSE, TRUE, CURRENT_TIMESTAMP, 'SYSTEM'),
    ('ROLE_DEVELOPER', 'Developer with API and resource access',   FALSE, TRUE, CURRENT_TIMESTAMP, 'SYSTEM');

INSERT INTO app_group (group_name, description, enabled, created_at, created_by) VALUES
    ('Administrators', 'System administrators group',  TRUE, CURRENT_TIMESTAMP, 'SYSTEM'),
    ('Managers',       'Team managers group',          TRUE, CURRENT_TIMESTAMP, 'SYSTEM'),
    ('Users',          'Standard users group',         TRUE, CURRENT_TIMESTAMP, 'SYSTEM'),
    ('Developers',     'Developers and engineers',     TRUE, CURRENT_TIMESTAMP, 'SYSTEM');

INSERT INTO group_roles (group_id, role_id, assigned_at, assigned_by)
SELECT g.group_id, r.role_id, CURRENT_TIMESTAMP, 'SYSTEM'
FROM app_group g, role r
WHERE (g.group_name = 'Administrators' AND r.role_name IN ('ROLE_ADMIN', 'ROLE_MANAGER', 'ROLE_USER'))
   OR (g.group_name = 'Managers'       AND r.role_name IN ('ROLE_MANAGER', 'ROLE_USER'))
   OR (g.group_name = 'Users'          AND r.role_name IN ('ROLE_USER'))
   OR (g.group_name = 'Developers'     AND r.role_name IN ('ROLE_DEVELOPER', 'ROLE_USER'));

INSERT INTO users (username, email, password, name, department, position, enabled, mfa_enabled, created_at) VALUES
    ('admin',       'admin@contexa.io',       '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'System Admin', 'IT',          'Administrator', TRUE, FALSE, CURRENT_TIMESTAMP),
    ('kim_manager', 'kim.manager@contexa.io', '$2a$10$dXJ3SW6G7P50lGmMQgel5uVf3JCDq1w3r4bXaECY5V5Q7Ggk3jYlC', 'Kim Jihoon',   'Finance',     'Manager',       TRUE, FALSE, CURRENT_TIMESTAMP),
    ('park_user',   'park.user@contexa.io',   '$2a$10$KkQZkYMGJPk7Xe1JhDcFGeYMM0E.VIiLvSdPqbMjPFHCdGo.ZsSXy', 'Park Minjun',  'Engineering', 'Developer',     TRUE, FALSE, CURRENT_TIMESTAMP),
    ('dev_lead',    'dev.lead@contexa.io',    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Lee Soyeon',   'Engineering', 'Tech Lead',     TRUE, FALSE, CURRENT_TIMESTAMP);

INSERT INTO user_groups (user_id, group_id, assigned_at, assigned_by)
SELECT u.id, g.group_id, CURRENT_TIMESTAMP, 'SYSTEM'
FROM users u, app_group g
WHERE (u.username = 'admin'       AND g.group_name = 'Administrators')
   OR (u.username = 'kim_manager' AND g.group_name = 'Managers')
   OR (u.username = 'park_user'   AND g.group_name = 'Users')
   OR (u.username = 'dev_lead'    AND g.group_name = 'Developers');
`;
}

function getEnterpriseDdlScript() {
  return `-- Contexa Enterprise DDL
-- See ddlScript-enterprise.sql for full schema
-- This is a placeholder - replace with actual enterprise DDL content
`;
}

function escapeRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

module.exports = { injectYml, injectMavenDep, injectGradleDep, generateDockerCompose, generateInitDbScripts };
