'use strict';

const fs = require('fs-extra');
const path = require('path');

const MARKER_START = '# --- Contexa AI Security ---';
const MARKER_END   = '# --- End Contexa ---';

const CONTEXA_GROUP_ID = 'io.contexa';
const CONTEXA_ARTIFACT_ID = 'spring-boot-starter-contexa';
const CONTEXA_VERSION = '0.1.0';

async function injectYml(ymlPath, opts = {}) {
  const { mode = 'shadow', llmProvider = 'ollama', llmModel = 'qwen2.5:7b',
          securityMode = 'full', infra = 'standalone' } = opts;

  // Build spring.ai block based on provider
  let aiBlock = '';
  if (llmProvider === 'ollama') {
    aiBlock = `
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: ${llmModel}
          keep-alive: "24h"
      embedding:
        enabled: true
        model: mxbai-embed-large
    anthropic:
      api-key: \${ANTHROPIC_API_KEY:your-anthropic-api-key}
      chat:
        enabled: false`;
  } else if (llmProvider === 'openai') {
    aiBlock = `
  ai:
    openai:
      api-key: \${OPENAI_API_KEY:}
      base-url: https://api.openai.com
      chat:
        options:
          model: ${llmModel}
          temperature: 0.3
        enabled: true
      embedding:
        enabled: false
    ollama:
      base-url: http://127.0.0.1:11434
      embedding:
        enabled: true
        model: mxbai-embed-large
      chat:
        options:
          model: qwen2.5:7b
          keep-alive: "24h"
    anthropic:
      api-key: \${ANTHROPIC_API_KEY:your-anthropic-api-key}
      chat:
        enabled: false`;
  } else if (llmProvider === 'anthropic') {
    aiBlock = `
  ai:
    anthropic:
      api-key: \${ANTHROPIC_API_KEY:}
      chat:
        enabled: true
        options:
          model: ${llmModel}
          temperature: 0.3
    ollama:
      base-url: http://127.0.0.1:11434
      embedding:
        enabled: true
        model: mxbai-embed-large
      chat:
        options:
          model: qwen2.5:7b
          keep-alive: "24h"`;
  }

  // Build datasource block
  const dsBlock = `
  datasource:
    url: jdbc:postgresql://localhost:5432/contexa
    username: contexa
    password: contexa1234!@#
    driver-class-name: org.postgresql.Driver`;

  // Build contexa block
  const priorityMap = {
    ollama: 'ollama,openai',
    openai: 'openai,ollama',
    anthropic: 'anthropic,ollama,openai',
  };

  const block = `\n${MARKER_START}
spring:${dsBlock}
${aiBlock}

contexa:
  zero-trust:
    enabled: true
    ai:
      chat:
        model:
          priority: ${priorityMap[llmProvider] || 'ollama,openai'}
${MARKER_END}`;

  await fs.ensureDir(path.dirname(ymlPath));

  if (await fs.pathExists(ymlPath)) {
    // Backup original
    await fs.copy(ymlPath, ymlPath + '.bak');

    let content = await fs.readFile(ymlPath, 'utf8');
    const regex = new RegExp(`${escapeRegex(MARKER_START)}[\\s\\S]*?${escapeRegex(MARKER_END)}`);
    content = content.match(regex)
      ? content.replace(regex, block.trim())
      : content + block;
    await fs.writeFile(ymlPath, content);
  } else {
    await fs.writeFile(ymlPath, block.trim());
  }
}

async function injectMavenDep(pomPath) {
  if (!await fs.pathExists(pomPath)) return false;
  let pom = await fs.readFile(pomPath, 'utf8');
  if (pom.includes(CONTEXA_ARTIFACT_ID)) return false;

  // Backup
  await fs.copy(pomPath, pomPath + '.bak');

  const dep = `
        <dependency>
            <groupId>${CONTEXA_GROUP_ID}</groupId>
            <artifactId>${CONTEXA_ARTIFACT_ID}</artifactId>
            <version>${CONTEXA_VERSION}</version>
        </dependency>`;
  pom = pom.replace('</dependencies>', `${dep}\n    </dependencies>`);
  await fs.writeFile(pomPath, pom);
  return true;
}

async function injectGradleDep(gradlePath) {
  if (!await fs.pathExists(gradlePath)) return false;
  let gradle = await fs.readFile(gradlePath, 'utf8');
  if (gradle.includes(CONTEXA_ARTIFACT_ID)) return false;

  // Backup
  await fs.copy(gradlePath, gradlePath + '.bak');

  gradle = gradle.replace(
    /dependencies\s*\{/,
    `dependencies {\n    implementation '${CONTEXA_GROUP_ID}:${CONTEXA_ARTIFACT_ID}:${CONTEXA_VERSION}'`
  );
  await fs.writeFile(gradlePath, gradle);
  return true;
}

async function generateDockerCompose(projectDir, opts = {}) {
  const { infra = 'standalone' } = opts;
  const composePath = path.join(projectDir, 'docker-compose.yml');

  if (await fs.pathExists(composePath)) {
    await fs.copy(composePath, composePath + '.bak');
  }

  let content = `# Contexa Infrastructure - Auto-generated by contexa init
services:
  # PostgreSQL with PGVector
  postgres:
    image: pgvector/pgvector:pg16
    container_name: contexa-postgres
    environment:
      POSTGRES_DB: contexa
      POSTGRES_USER: contexa
      POSTGRES_PASSWORD: contexa1234!@#
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contexa -d contexa"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Ollama - Local LLM for AI security analysis
  ollama:
    image: ollama/ollama:latest
    container_name: contexa-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=30m
      - OLLAMA_NUM_PARALLEL=2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
`;

  if (infra === 'distributed') {
    content += `
  # Redis - Session store, cache, distributed locks
  redis:
    image: redis:7.2-alpine
    container_name: contexa-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Zookeeper - Kafka coordinator
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: contexa-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  # Kafka - Event streaming
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: contexa-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
`;
  }

  // Volumes
  content += `
volumes:
  pgdata:
  ollama-data:`;

  if (infra === 'distributed') {
    content += `
  redis-data:
  zookeeper-data:
  kafka-data:`;
  }

  content += '\n';

  await fs.writeFile(composePath, content);
  return composePath;
}

function escapeRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

module.exports = { injectYml, injectMavenDep, injectGradleDep, generateDockerCompose };
